" BEGIN VUNDLE----------------------------------------------------------------
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" Allow Ctl + direction (hjkl) to switch panes between vim & tmux
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'ctrlpvim/ctrlp.vim'
" surround is for chaning quotes and brackets and such
Plugin 'tpope/vim-surround'
" repeat makes the . command work for surround commands
Plugin 'tpope/vim-repeat'
" Handy rails stuff
Plugin 'tpope/vim-rails'
" Auto-complete with tab
Plugin 'ervandew/supertab'
" Fancy status lines
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
let g:airline_powerline_fonts = 1
let g:airline_theme='jellybeans'

" Git info in the powerline and git commands like :Gblame
Plugin 'tpope/vim-fugitive'

" Git modification info in the gutters
Plugin 'airblade/vim-gitgutter'
set updatetime=750 " ensures that line markers show up relatively quickly
let g:gitgutter_terminal_reports_focus=0
set signcolumn=yes " always show the column for git line changes

" Syntax checker
Plugin 'vim-syntastic/syntastic'

" Help vim be able to see file changes
Plugin 'wincent/terminus'

" Automatically add end lines to if statements and what not
Plugin 'tpope/vim-endwise'

" Commenting fun
Plugin 'scrooloose/nerdcommenter'

" Preview colors in csss
Plugin 'ap/vim-css-color'

" Ability to run some unix commands from inside vim, mostly for moving,
" deleting, chmoding files and what not.
Plugin 'tpope/vim-eunuch'

" Keep aware of trailing whitespace
Plugin 'bronson/vim-trailing-whitespace'

" A color scheme
Plugin 'nanotech/jellybeans.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
" END VUNDLE----------------------------------------------------------------
"
" Much of the remaining comes from : https://dougblack.io/words/a-good-vimrc.html
" Enable syntax highlighting
syntax on

" Leader {{{
" Map the leader key to ,
let mapleader = ","
" }}}

" UI Config {{{
colorscheme jellybeans
set cursorline          " highlight current line
hi CursorLine   cterm=none ctermbg=234 ctermfg=NONE guibg=black gui=none
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]
set encoding=UTF-8
set ttyfast
set splitbelow
set splitright
set nowrap
" }}}

" Searching {{{
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
" turn off search highlight by doing ,<space>
nnoremap <leader><space> :nohlsearch<CR>
set ignorecase
set smartcase
set grepprg=ag\ --nogroup\ --nocolor
" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
" The following requies: brew install fzy
function! FzyCommand(choice_command, vim_command)
  try
    let output = system(a:choice_command . " | fzy ")
  catch /Vim:Interrupt/
    " Swallow errors from ^C, allow redraw! below
  endtry
  redraw!
  if v:shell_error == 0 && !empty(output)
    exec a:vim_command . ' ' . output
  endif
endfunction
nnoremap <leader>e :call FzyCommand("ag . --silent -l -g ''", ":e")<cr>
nnoremap <leader>v :call FzyCommand("ag . --silent -l -g ''", ":vs")<cr>
nnoremap <leader>s :call FzyCommand("ag . --silent -l -g ''", ":sp")<cr>
" }}}

" Folding {{{
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
" space open/closes folds
nnoremap <space> za
set foldmethod=indent   " fold based on indent level
" }}}

" Movement {{{
" move to beginning/end of line
nnoremap B ^
nnoremap E $
" highlight last inserted text
nnoremap gV `[v`]
" }}}

" Shortcuts {{{
" jk is escape
inoremap jk <esc>
" }}}

" Ctrl-P settings {{{
let g:ctrlp_match_window = 'bottom,order:ttb,max:40,results:20'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0
" Make CtrlP use ag for listing the files. Way faster and no useless files.
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
" brew install ripgrep
if executable('rg')
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
endif
let g:ctrlp_use_caching = 0
" Ignore some stuff
set wildignore+=*/.git/*,*/tmp/*,*.swp " Things to ignore when listing files and such
" }}}

" Tmux {{{
" allows cursor change in tmux mode
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif
" }}}

" Line Number {{{
set number
" }}}

" Test running {{{
" Vim functions to run RSpec and Cucumber on the current file and optionally on
" the spec/scenario under the cursor.

function! RailsScriptIfExists(name)
  " Bundle exec
  if isdirectory(".bundle") || (exists("b:rails_root") && isdirectory(b:rails_root . "/.bundle"))
    return "bundle exec " . a:name
  " System Binary
  else
    return a:name
  end
endfunction

function! RunSpec(args)
  let spec = RailsScriptIfExists("rspec --drb")
  let cmd = spec . " " . " -fd -c " . @% . a:args
  execute ":! echo " . cmd . " && " . cmd
endfunction

function! RunCucumber(args)
  let cucumber = RailsScriptIfExists("cucumber")
  let cmd = cucumber . " " . @% . a:args
  execute ":! echo " . cmd . " && " . cmd
endfunction

function! RunTestFile(args)
  if @% =~ "\.feature$"
    call RunCucumber("" . a:args)
  elseif @% =~ "\.rb$"
    call RunSpec("" . a:args)
  end
endfunction

function! RunTest(args)
  if @% =~ "\.feature$"
    call RunCucumber(":" . line('.') . a:args)
  elseif @% =~ "\.rb$"
    call RunSpec(":" . line('.') . a:args)
  end
endfunction

function! RunAllSpecs(args)
  let spec = RailsScriptIfExists("rspec --drb")
  let cmd = spec . " " . " -fd -c "
  execute ":! echo " . cmd . " && " . cmd
endfunction

function! RunAllCucumber(args)
  let cucumber = RailsScriptIfExists("cucumber")
  let cmd = cucumber . " " . " -c "
  execute ":! echo " . cmd . " && " . cmd
endfunction

function! RunRake(args)
  let rake = RailsScriptIfExists("rake")
  let cmd = rake
  execute ":! echo " . cmd . " && " . cmd
endfunction


map <Leader>t :call RunTest("")<CR>
map <Leader>T :call RunTestFile("")<CR>
map <Leader>rs :call RunAllSpecs("")<CR>
map <Leader>rc :call RunAllCucumber("")<CR>
map <Leader>ra :call RunRake("")<CR>
" }}}

" File reloading {{{
set autoread
" Triger `autoread` when files changes on disk
" https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
" https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif
" Notification after file change
" https://vi.stackexchange.com/questions/13091/autocmd-event-for-autoread
autocmd FileChangedShellPost *
  \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None
" }}}

" Syntastic config {{{
" https://github.com/vim-syntastic/syntastic#3-recommended-settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" }}}
" To investigate:
"
" vimux - run commands directly in vim into a tmux pane :
" https://www.bugsnag.com/blog/tmux-and-vim
" https://github.com/benmills/vimux
"
" Motions for Ruby blocks
" https://github.com/nelstrom/vim-textobj-rubyblock
"
" Multiple cursors - edit multiple lines at a time
" https://github.com/terryma/vim-multiple-cursors
"
" Vim sensible - would this be helpful?
" https://github.com/tpope/vim-sensible
"
" Plugin for running ruby tests - Seems like rails.vim may do some/most of this?
" https://github.com/skalnik/vim-vroom
"
"
"
"
"
" Are there other good things I could pull from these?
" https://c7.se/switching-to-vundle/
" https://vim.spf13.com
"
"
"
" modeline to allow folding by marked section
" vim:foldmethod=marker:foldlevel=0
