#enables color in the terminal bash shell export
CLICOLOR=1
#sets up the color scheme for list export
export LSCOLORS=gxfxcxdxbxegedabagacad
#sets up the prompt color (currently a green similar to linux terminal)
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '
#enables color for iTerm
export TERM=xterm-color
#sets up proper alias commands when called
alias ls='ls -GFh'
alias ll='ls -hl'

# enable vi mode
# https://catonmat.net/bash-vi-editing-mode-cheat-sheet
# https://catonmat.net/ftp/bash-vi-editing-mode-cheat-sheet.pdf
set -o vi


# Get lots of colors
TERM=screen-256color


# a couple of convenience aliases for puma-dev
alias kill_puma="pkill -USR1 puma-dev"
alias tail_puma="tail -f ~/Library/Logs/puma-dev.log"

# NVM stuff - Can we put this somewhere else? Doesn't seem like the kind of thing I want to version...
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

