# Keep actual customizations in bashrc and source them from here since MacOS is weird.
if [ -r ~/.bashrc ]; then
   source ~/.bashrc
fi

# Anything system specifig and/or private can go in ~/.bashrc.local and doesn't end
# up in source control.
if [ -r ~/.bashrc.local ]; then
   source ~/.bashrc.local
fi

eval "$(rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jgreen/projects/google-cloud-sdk/path.bash.inc' ]; then . '/Users/jgreen/projects/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jgreen/projects/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/jgreen/projects/google-cloud-sdk/completion.bash.inc'; fi
